#spring:
#  cache:
#    type: redis
#  redis:
#    host: redis-study.f8bac8.ng.0001.apn2.cache.amazonaws.com
#    port: 6379

spring:
  redis:
    host: redis-study.f8bac8.ng.0001.apn2.cache.amazonaws.com
    port: 6379